site_name: Методичка по Парсингу
site_url: https://useuseless.github.io/data-collect-manual/

repo_name: useuseless/data-collect-manual
repo_url: https://github.com/useuseless/data-collect-manual
edit_uri: edit/main/docs/ # Ссылка, чтобы править файл прямо в браузере

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/useuseless
      name: My GitHub
    - icon: fontawesome/brands/telegram
      link: https://t.me/ldv92
      name: Telegram Channel

theme:
  name: material
  language: ru
  palette: 
    # Темная тема
    - scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Светлая тема (По умолчанию)
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.expand # Раскрывать меню
    - navigation.sections # Секции меню
    - content.code.copy # Кнопка копирования кода (удобно для твоих шаблонов!)

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences # Чтобы блоки кода работали корректно
  - admonition # Чтобы делать красивые блоки "Внимание!" и "Совет"

nav:
  - 'Главная': index.md
  
  - 'Старт':
      - 'Инструкция по анализу': analysis_guide.md
      - 'Обзор инструментов': tools_overview.md

  - 'Часть 1: Теория и База':
      - 'Блок 1: Анатомия Жертвы':
          - '1. Введение (SSR vs CSR)': topic_01_intro.md
          - '2. Скрытые данные (JSON)': topic_02_hidden_json.md
          - '3. Протоколы (HTTP/2)': topic_03_protocols.md
      - 'Блок 2: Арсенал':
          - '4. Клиенты (Requests/Aiohttp)': topic_04_clients.md
          - '5. Парсеры (BS4/LXML)': topic_05_parsers.md
          - '6. Браузеры (Selenium/Playwright)': topic_06_browsers.md
          - '7. Спецназ (DrissionPage)': topic_07_drission.md
      - 'Блок 3: Взлом и Защита':
          - '8. Revers Engineering API': topic_08_reverse_api.md
          - '9. Анти-бот (JA3/TLS)': topic_09_antibot.md
          - '10. Прокси и Ротация': topic_10_proxy.md
      - 'Блок 4: Архитектура':
          - '11. Структуры (Pydantic)': topic_11_pydantic.md
          - '12. Архитектура (Producer/Consumer)': topic_12_architecture.md
      - 'Блок 5: Логистика':
          - '13. Авторизация и Куки': topic_13_auth.md
          - '14. Сохранение (DB/Files)': topic_14_storage.md

  - 'Часть 2: Шаблоны (Copy-Paste)':
      - 'Шаблон 1: Direct API': tool_01_api.md
      - 'Шаблон 2: Hidden JSON': tool_02_json.md
      - 'Шаблон 3: Static HTML': tool_03_html.md
      - 'Шаблон 4: TLS Impersonation': tool_04_tls.md
      - 'Шаблон 5: Headless Browser': tool_05_browser.md
      - 'Шаблон 6: Anti-Bot Bypass': tool_06_stealth.md
      - 'Шаблон 7: WebSockets': tool_07_websockets.md
      - 'Шаблон 8: Mobile API': tool_08_mobile.md